export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_LOADED = "CATEGORIES_LOADED";
export const ADMIN_ADD_NEW_CATEGORY_SUCCESS = "ADMIN_ADD_NEW_CATEGORY_SUCCESS";
export const ADMIN_ADD_NEW_CATEGORY_FAIL = "ADMIN_ADD_NEW_CATEGORY_FAIL";
export const ADMIN_GET_CATEGORY_TO_BE_EDITED =
  "ADMIN_GET_CATEGORY_TO_BE_EDITED";
export const ADMIN_EDITED_CATEGORY_SUCCESS = "ADMIN_EDITED_CATEGORY_SUCCESS";
export const ADMIN_EDITED_CATEGORY_FAIL = "ADMIN_EDITED_CATEGORY_FAIL";
export const CLEAR_MSG_FROM_CATEGORIES = "CLEAR_MSG_FROM_CATEGORIES";
export const ADMIN_DELETE_CATEGORY = "ADMIN_DELETE_CATEGORY";

export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export const GET_PRODUCTS_FROM_CATEGORY = "GET_PRODUCTS_FROM_CATEGORY";

export const FAVORITES_LOADING = "FAVORITES_LOADING";
export const FAVORITES_LOADED = "FAVORITES_LOADED";
export const ADD_PRODUCT_TO_FAVORITE = "ADD_PRODUCT_TO_FAOVIRITE";
export const REMOVE_FAVORITE_PRODUCT = "REMOVE_FAVORITE_PRODUCT";

export const CART_LOADING = "CART_LOADING";
export const CART_LOADED = "CART_LOADED";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DECREASE_QUANTITY_PRODUCT_CART = "DECREASE_QUANTITY_PRODUCT_CART";
export const INCREASE_QUANTITY_PRODUCT_CART = "INCREASE_QUANTITY_PRODUCT_CART";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";

export const SELECTED_PRODUCT_LOADING = "SELECTED_PRODUCT_LOADING";
export const SELECTED_PRODUCT_LOADED = "SELECTED_PRODUCT_LOADED";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const UPDATE_PERSONAL_DATA_SUCCESS = "UPDATE_PERSONAL_DATA_SUCCESS";
export const UPDATE_PERSONAL_DATA_FAIL = "UPDATE_PERSONAL_DATA_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIl";

export const RECOVER_SUCCESS = "RECOVER_SUCCESS";
export const CLEAR_RECOVER_MESSAGE = "CLEAR_RECOVER_MESSAGE";
export const RECOVER_FAIL = "RECOVER_FAIL";
export const CHECK_IF_TOKEN_IS_NOT_EXPIRE = "CHECK_IF_TOKEN_IS_NOT_EXPIRE";
export const CHECK_IF_TOKEN_IS_NOT_EXPIRE_FAIL =
  "CHECK_IF_TOKEN_IS_NOT_EXPIRE_FAIL";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const USERS_LOADING = "USERS_LOADING";
export const USERS_LOADED = "USERS_LOADED";

export const ADMINS_LOADING = "ADMINS_LOADING";
export const ADMINS_LOADED = "ADMINS_LOADED";

export const REVIEWS_LOADING = "REVIEWS_LOADING";
export const REVIEWS_LOADED = "REVIEWS_LOADED";
export const GET_REVIEWS_PRODUCT = "GET_REVIEWS_PRODUCT";
export const GET_ALL_USER_REVIEWS_SUCCESS = "GET_ALL_USER_REVIEWS_SUCCESS";
export const ADMIN_MODERATE_REVIEW = "ADMIN_MODERATE_REVIEW";
export const ADMIN_UNMODERATE_REVIEW = "ADMIN_UNMODERATE_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const ADMIN_DELETE_REVIEWS = "ADMIN_DELETE_REVIEWS";

export const SWITCH_ROLE_TO_ADMIN = "SWITCH_ROLE_TO_ADMIN";
export const SWITCH_ROLE_TO_USER = "SWITCH_ROLE_TO_USER";

export const ADMIN_DELETE_USER = "ADMIN_DELETE_USER";
export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS";
export const ADMIN_ADD_PRODUCT_FAIl = "ADMIN_ADD_PRODUCT_FAIl";
export const ADMIN_EDIT_PRODUCT_SUCCESS = "ADMIN_EDIT_PRODUCT_SUCCESS";
export const ADMIN_EDIT_PRODUCT_FAIL = "ADMIN_EDIT_PRODUCT_FAIL";
export const ADMIN_DELETE_PRODUCT = "ADMIN_DELETE_PRODUCT";

export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAIL = "POST_REVIEW_FAIL";

export const GET_DETAILS_LOGGED = "GET_DETAILS_LOGGED";

export const AVATAR_UPDATED_SUCCESS = "AVATAR_UPDATED_SUCCESS";
export const AVATAR_UPDATED_FAIL = "AVATAR_UPDATED_FAIL";

export const POST_NEW_ADDRESS_SUCCESS = "POST_NEW_ADDRESS_SUCCESS";
export const POST_NEW_ADDRESS_FAIL = "POST_NEW_ADDRESS_FAIL";

export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";
